# Generated by Django 3.2.8 on 2021-10-11 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("NOT_ACTIVE", "Not Active")],
                        max_length=255,
                    ),
                ),
                ("birth_date", models.DateField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rg", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("marital_status", models.CharField(max_length=255)),
                ("profession", models.CharField(max_length=255)),
                ("sex", models.CharField(max_length=255)),
                ("mothers_name", models.CharField(max_length=255)),
                ("fathers_name", models.CharField(max_length=255)),
                ("observations", models.CharField(max_length=255)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="client.client"
                    ),
                ),
            ],
        ),
    ]
